# Generated by Django 6.0.3 on 2026-03-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('filepath', models.CharField(max_length=500, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('c', 'Current'), ('a', 'Archived')], default='c', max_length=1)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', 'filename'],
            },
        ),
    ]
